language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '10'
    - node_js: '11'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: "qKyFZ0Rxn4/GqwD/IwdYwMqvefYGEgcNY/Mqh4QaW7Q795LR19OSf7wv/oYia6O2d4G4o3OHxTvfO1V1uJHKxak5Z4o9swWglf0YpjbzbDFBeMeFf2vgDtRoE07ZtsHO6qzo6wLb3G763rugog9skmvBJcsEtI9eUFSiRI89AZaSZW5r3aDMTvsJg0BjbxJ59o0VoUt+BJ1kmXPRgpOb3yVnt+YsAdzlhuZwS067HJPuwqlsAV95/CPzl6Uk8vwc1HVsfppGi9UrJw/va4e23O/tJEWWf6xH9Jx5Bh3t1/X+Gku7H/ztu1QyqBlnK9nWKTBg9h+a2dyffhaDA/ntyk7qSgN42eaFcCw+FEfFZ0gHBINnDlvaO07+7lB4hg702EZ9hVxS/gTSSsC2aOptOaYtaayLpxOLbujjMNzp3iOatneHTwsJiO2wresDOHmNwpBR0i1AFTgOMcGvW1qTkHcTDkngaoYRn064ljo587WR4Cf+YSO0L6nOddFZOKpz0fO4BOfVrP8DFzzADCalc1gxXWui+wmvMWLHWl13Ub5kNq+2jHZuCMpaUePKqSAg1bN5IZfahyx0jxK8JyTiN2J4vsZLylaXnoj7EQw7bvJaptky82yHkDWlFDIqPCVzTdrGXCqqyvF3XQSGTFPQF0GVzfUo7FLLy3IhQ0jTWTc="
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
